using System.Drawing;

namespace BonsaiGotchi.Properties
{
    /// <summary>
    /// Placeholder for resources. In a real project, this would be generated by Visual Studio.
    /// </summary>
    internal static class Resources
    {
        // A simple icon placeholder
        public static Icon BonsaiIcon => SystemIcons.Application;
    }
}